#Install liquibase CLI on Mac:  brew install liquibase
#Install liquibase CLI on Windows: choco install liquibase
#check version: liquibase --version

#cd to project directory where have liquibase.properties file to run liquibase cli

#liquibase update	               Áp d?ng thay ??i database theo changelog
#liquibase status	               Xem nh?ng thay ??i nào ch?a ???c áp d?ng
#liquibase rollbackCount 1	       Quay l?i 1 changeSet tr??c ?ó
#liquibase generateChangeLog	   T?o file changelog t? database hi?n t?i
#liquibase diffChangeLog	       So sánh DB hi?n t?i v?i tr?ng thái tr??c ?ó
#liquibase history	               Xem l?ch s? các thay ??i ?ã ch?y


#if not config cd to /src/main/resources where have liquibase.properties file
#liquibase --url=jdbc:mariadb://localhost:3306/ecommerce_shopping \
#  --username=root --password=monkey3110 \
#  --changeLogFile=db/changelog/changelog-master.xml \
#  update

#config liquibase
#run command: liquibase update
url=jdbc:mariadb://localhost:3306/ecommerce_shopping
username=root
password=monkey3110
driver=org.mariadb.jdbc.Driver
changeLogFile=db/changelog/changelog-master.xml